//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRegistroCivil
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.registrocivil.gob.ec", ConfigurationName="WSRegistroCivil.WSRegistroCivilConsulta")]
    public interface WSRegistroCivilConsulta
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorNombre", ReplyAction="http://www.registrocivil.gob.ec/WSRegistroCivilConsulta/BusquedaPorNombreResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreResponse> BusquedaPorNombreAsync(WSRegistroCivil.BusquedaPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/WSRegistroCivilConsulta/WsUpRequest", ReplyAction="http://www.registrocivil.gob.ec/WSRegistroCivilConsulta/WsUpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSRegistroCivil.WsUpResponse> WsUpAsync(WSRegistroCivil.WsUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorCedula", ReplyAction="http://www.registrocivil.gob.ec/WSRegistroCivilConsulta/BusquedaPorCedulaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorCedulaResponse> BusquedaPorCedulaAsync(WSRegistroCivil.BusquedaPorCedulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorNombreInscrito", ReplyAction="http://www.registrocivil.gob.ec/WSRegistroCivilConsulta/BusquedaPorNombreInscrito" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreInscritoResponse> BusquedaPorNombreInscritoAsync(WSRegistroCivil.BusquedaPorNombreInscritoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.registrocivil.gob.ec")]
    public partial class ciudadanos
    {
        
        private string codigoErrorField;
        
        private string errorField;
        
        private string firmaElectronicaField;
        
        private inscrito[] inscritoField;
        
        private persona[] personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inscrito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public inscrito[] inscrito
        {
            get
            {
                return this.inscritoField;
            }
            set
            {
                this.inscritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public persona[] persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.registrocivil.gob.ec")]
    public partial class inscrito
    {
        
        private string actaField;
        
        private string actaDefuncionField;
        
        private string anioInscripcionField;
        
        private string claseField;
        
        private string claseDefuncionField;
        
        private string codigoCondicionNacidoField;
        
        private string codigoErrorField;
        
        private string codigoGeneroField;
        
        private string codigoLugarDefuncionField;
        
        private string codigoLugarInscripcionField;
        
        private string codigoLugarInscripcionFallecimientoField;
        
        private string codigoLugarNacimientoField;
        
        private string codigoNacionalidadMadreField;
        
        private string codigoNacionalidadPadreField;
        
        private string condicionNacidoField;
        
        private string errorField;
        
        private string fechaActualizacionField;
        
        private string fechaDefuncionField;
        
        private string fechaIngresoField;
        
        private string fechaInscripcionFallecimientoField;
        
        private string fechaNacimientoField;
        
        private string generoField;
        
        private string lugarDefuncionField;
        
        private string lugarInscripcionField;
        
        private string lugarInscripcionFallecimientoField;
        
        private string lugarNacimientoField;
        
        private string nacionalidadMadreField;
        
        private string nacionalidadPadreField;
        
        private string nombreField;
        
        private string nombreMadreField;
        
        private string nombrePadreField;
        
        private string paginaField;
        
        private string paginaDefuncionField;
        
        private string tomoField;
        
        private string tomoDefuncionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Acta
        {
            get
            {
                return this.actaField;
            }
            set
            {
                this.actaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ActaDefuncion
        {
            get
            {
                return this.actaDefuncionField;
            }
            set
            {
                this.actaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AnioInscripcion
        {
            get
            {
                return this.anioInscripcionField;
            }
            set
            {
                this.anioInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Clase
        {
            get
            {
                return this.claseField;
            }
            set
            {
                this.claseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ClaseDefuncion
        {
            get
            {
                return this.claseDefuncionField;
            }
            set
            {
                this.claseDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CodigoCondicionNacido
        {
            get
            {
                return this.codigoCondicionNacidoField;
            }
            set
            {
                this.codigoCondicionNacidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CodigoGenero
        {
            get
            {
                return this.codigoGeneroField;
            }
            set
            {
                this.codigoGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CodigoLugarDefuncion
        {
            get
            {
                return this.codigoLugarDefuncionField;
            }
            set
            {
                this.codigoLugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CodigoLugarInscripcion
        {
            get
            {
                return this.codigoLugarInscripcionField;
            }
            set
            {
                this.codigoLugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CodigoLugarInscripcionFallecimiento
        {
            get
            {
                return this.codigoLugarInscripcionFallecimientoField;
            }
            set
            {
                this.codigoLugarInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CodigoLugarNacimiento
        {
            get
            {
                return this.codigoLugarNacimientoField;
            }
            set
            {
                this.codigoLugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CodigoNacionalidadMadre
        {
            get
            {
                return this.codigoNacionalidadMadreField;
            }
            set
            {
                this.codigoNacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CodigoNacionalidadPadre
        {
            get
            {
                return this.codigoNacionalidadPadreField;
            }
            set
            {
                this.codigoNacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CondicionNacido
        {
            get
            {
                return this.condicionNacidoField;
            }
            set
            {
                this.condicionNacidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string FechaActualizacion
        {
            get
            {
                return this.fechaActualizacionField;
            }
            set
            {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string FechaDefuncion
        {
            get
            {
                return this.fechaDefuncionField;
            }
            set
            {
                this.fechaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string FechaIngreso
        {
            get
            {
                return this.fechaIngresoField;
            }
            set
            {
                this.fechaIngresoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string FechaInscripcionFallecimiento
        {
            get
            {
                return this.fechaInscripcionFallecimientoField;
            }
            set
            {
                this.fechaInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string LugarDefuncion
        {
            get
            {
                return this.lugarDefuncionField;
            }
            set
            {
                this.lugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string LugarInscripcion
        {
            get
            {
                return this.lugarInscripcionField;
            }
            set
            {
                this.lugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string LugarInscripcionFallecimiento
        {
            get
            {
                return this.lugarInscripcionFallecimientoField;
            }
            set
            {
                this.lugarInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string LugarNacimiento
        {
            get
            {
                return this.lugarNacimientoField;
            }
            set
            {
                this.lugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string NacionalidadMadre
        {
            get
            {
                return this.nacionalidadMadreField;
            }
            set
            {
                this.nacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string NacionalidadPadre
        {
            get
            {
                return this.nacionalidadPadreField;
            }
            set
            {
                this.nacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string NombreMadre
        {
            get
            {
                return this.nombreMadreField;
            }
            set
            {
                this.nombreMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string NombrePadre
        {
            get
            {
                return this.nombrePadreField;
            }
            set
            {
                this.nombrePadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string PaginaDefuncion
        {
            get
            {
                return this.paginaDefuncionField;
            }
            set
            {
                this.paginaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Tomo
        {
            get
            {
                return this.tomoField;
            }
            set
            {
                this.tomoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string TomoDefuncion
        {
            get
            {
                return this.tomoDefuncionField;
            }
            set
            {
                this.tomoDefuncionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.registrocivil.gob.ec")]
    public partial class persona
    {
        
        private string actaField;
        
        private string actaDefuncionField;
        
        private string actaMatrimonioField;
        
        private string anioInscripcionField;
        
        private string cIConyugeField;
        
        private string cIMadreField;
        
        private string cIPadreField;
        
        private string cMP1Field;
        
        private string cMP10Field;
        
        private string cMP2Field;
        
        private string cMP3Field;
        
        private string cMP4Field;
        
        private string cMP5Field;
        
        private string cMP6Field;
        
        private string cMP7Field;
        
        private string cMP8Field;
        
        private string cMP9Field;
        
        private string calleField;
        
        private string cedulaField;
        
        private string claseField;
        
        private string claseDefuncionField;
        
        private string claseMatrimonioField;
        
        private string codigoCondicionCeduladoField;
        
        private string codigoDomicilioField;
        
        private string codigoErrorField;
        
        private string codigoEstadoCivilField;
        
        private string codigoGeneroField;
        
        private string codigoInstruccionField;
        
        private string codigoLugarDefuncionField;
        
        private string codigoLugarInscripcionField;
        
        private string codigoLugarInscripcionFallecimientoField;
        
        private string codigoLugarMatrimonioField;
        
        private string codigoLugarNacimientoField;
        
        private string codigoNacionalidadField;
        
        private string codigoNacionalidadMadreField;
        
        private string codigoNacionalidadPadreField;
        
        private string codigoProfesionField;
        
        private string condicionCeduladoField;
        
        private string conyugeField;
        
        private string domicilioField;
        
        private string errorField;
        
        private string estadoCivilField;
        
        private string estadoMagnaField;
        
        private string fechaActualizacionField;
        
        private string fechaCedulacionField;
        
        private string fechaDefuncionField;
        
        private string fechaInscripcionFallecimientoField;
        
        private string fechaMatrimonioField;
        
        private string fechaNacimientoField;
        
        private byte[] firmaField;
        
        private string firmaElectronicaField;
        
        private byte[] fotografiaField;
        
        private string generoField;
        
        private byte[] huellaField;
        
        private string individualDactilarField;
        
        private string instruccionField;
        
        private string lugarDefuncionField;
        
        private string lugarInscripcionField;
        
        private string lugarInscripcionFallecimientoField;
        
        private string lugarMatrimonioField;
        
        private string lugarNacimientoField;
        
        private string nacionalidadField;
        
        private string nacionalidadMadreField;
        
        private string nacionalidadPadreField;
        
        private string nombreField;
        
        private string nombreMadreField;
        
        private string nombrePadreField;
        
        private string numeroCasaField;
        
        private string observacionField;
        
        private string observacionInstitucionField;
        
        private string paginaField;
        
        private string paginaDefuncionField;
        
        private string paginaMatrimonioField;
        
        private string profesionField;
        
        private string tomoField;
        
        private string tomoDefuncionField;
        
        private string tomoMatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Acta
        {
            get
            {
                return this.actaField;
            }
            set
            {
                this.actaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ActaDefuncion
        {
            get
            {
                return this.actaDefuncionField;
            }
            set
            {
                this.actaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ActaMatrimonio
        {
            get
            {
                return this.actaMatrimonioField;
            }
            set
            {
                this.actaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AnioInscripcion
        {
            get
            {
                return this.anioInscripcionField;
            }
            set
            {
                this.anioInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CIConyuge
        {
            get
            {
                return this.cIConyugeField;
            }
            set
            {
                this.cIConyugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CIMadre
        {
            get
            {
                return this.cIMadreField;
            }
            set
            {
                this.cIMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CIPadre
        {
            get
            {
                return this.cIPadreField;
            }
            set
            {
                this.cIPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CMP1
        {
            get
            {
                return this.cMP1Field;
            }
            set
            {
                this.cMP1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CMP10
        {
            get
            {
                return this.cMP10Field;
            }
            set
            {
                this.cMP10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CMP2
        {
            get
            {
                return this.cMP2Field;
            }
            set
            {
                this.cMP2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CMP3
        {
            get
            {
                return this.cMP3Field;
            }
            set
            {
                this.cMP3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CMP4
        {
            get
            {
                return this.cMP4Field;
            }
            set
            {
                this.cMP4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CMP5
        {
            get
            {
                return this.cMP5Field;
            }
            set
            {
                this.cMP5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CMP6
        {
            get
            {
                return this.cMP6Field;
            }
            set
            {
                this.cMP6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CMP7
        {
            get
            {
                return this.cMP7Field;
            }
            set
            {
                this.cMP7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CMP8
        {
            get
            {
                return this.cMP8Field;
            }
            set
            {
                this.cMP8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CMP9
        {
            get
            {
                return this.cMP9Field;
            }
            set
            {
                this.cMP9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Cedula
        {
            get
            {
                return this.cedulaField;
            }
            set
            {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Clase
        {
            get
            {
                return this.claseField;
            }
            set
            {
                this.claseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ClaseDefuncion
        {
            get
            {
                return this.claseDefuncionField;
            }
            set
            {
                this.claseDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ClaseMatrimonio
        {
            get
            {
                return this.claseMatrimonioField;
            }
            set
            {
                this.claseMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CodigoCondicionCedulado
        {
            get
            {
                return this.codigoCondicionCeduladoField;
            }
            set
            {
                this.codigoCondicionCeduladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CodigoDomicilio
        {
            get
            {
                return this.codigoDomicilioField;
            }
            set
            {
                this.codigoDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CodigoEstadoCivil
        {
            get
            {
                return this.codigoEstadoCivilField;
            }
            set
            {
                this.codigoEstadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string CodigoGenero
        {
            get
            {
                return this.codigoGeneroField;
            }
            set
            {
                this.codigoGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string CodigoInstruccion
        {
            get
            {
                return this.codigoInstruccionField;
            }
            set
            {
                this.codigoInstruccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string CodigoLugarDefuncion
        {
            get
            {
                return this.codigoLugarDefuncionField;
            }
            set
            {
                this.codigoLugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CodigoLugarInscripcion
        {
            get
            {
                return this.codigoLugarInscripcionField;
            }
            set
            {
                this.codigoLugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CodigoLugarInscripcionFallecimiento
        {
            get
            {
                return this.codigoLugarInscripcionFallecimientoField;
            }
            set
            {
                this.codigoLugarInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string CodigoLugarMatrimonio
        {
            get
            {
                return this.codigoLugarMatrimonioField;
            }
            set
            {
                this.codigoLugarMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string CodigoLugarNacimiento
        {
            get
            {
                return this.codigoLugarNacimientoField;
            }
            set
            {
                this.codigoLugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string CodigoNacionalidad
        {
            get
            {
                return this.codigoNacionalidadField;
            }
            set
            {
                this.codigoNacionalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string CodigoNacionalidadMadre
        {
            get
            {
                return this.codigoNacionalidadMadreField;
            }
            set
            {
                this.codigoNacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string CodigoNacionalidadPadre
        {
            get
            {
                return this.codigoNacionalidadPadreField;
            }
            set
            {
                this.codigoNacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string CodigoProfesion
        {
            get
            {
                return this.codigoProfesionField;
            }
            set
            {
                this.codigoProfesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string CondicionCedulado
        {
            get
            {
                return this.condicionCeduladoField;
            }
            set
            {
                this.condicionCeduladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Conyuge
        {
            get
            {
                return this.conyugeField;
            }
            set
            {
                this.conyugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string EstadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string EstadoMagna
        {
            get
            {
                return this.estadoMagnaField;
            }
            set
            {
                this.estadoMagnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string FechaActualizacion
        {
            get
            {
                return this.fechaActualizacionField;
            }
            set
            {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string FechaCedulacion
        {
            get
            {
                return this.fechaCedulacionField;
            }
            set
            {
                this.fechaCedulacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string FechaDefuncion
        {
            get
            {
                return this.fechaDefuncionField;
            }
            set
            {
                this.fechaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string FechaInscripcionFallecimiento
        {
            get
            {
                return this.fechaInscripcionFallecimientoField;
            }
            set
            {
                this.fechaInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string FechaMatrimonio
        {
            get
            {
                return this.fechaMatrimonioField;
            }
            set
            {
                this.fechaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string FechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=49)]
        public byte[] Firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string FirmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=51)]
        public byte[] Fotografia
        {
            get
            {
                return this.fotografiaField;
            }
            set
            {
                this.fotografiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string Genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=53)]
        public byte[] Huella
        {
            get
            {
                return this.huellaField;
            }
            set
            {
                this.huellaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string IndividualDactilar
        {
            get
            {
                return this.individualDactilarField;
            }
            set
            {
                this.individualDactilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string Instruccion
        {
            get
            {
                return this.instruccionField;
            }
            set
            {
                this.instruccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string LugarDefuncion
        {
            get
            {
                return this.lugarDefuncionField;
            }
            set
            {
                this.lugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string LugarInscripcion
        {
            get
            {
                return this.lugarInscripcionField;
            }
            set
            {
                this.lugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string LugarInscripcionFallecimiento
        {
            get
            {
                return this.lugarInscripcionFallecimientoField;
            }
            set
            {
                this.lugarInscripcionFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string LugarMatrimonio
        {
            get
            {
                return this.lugarMatrimonioField;
            }
            set
            {
                this.lugarMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string LugarNacimiento
        {
            get
            {
                return this.lugarNacimientoField;
            }
            set
            {
                this.lugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string Nacionalidad
        {
            get
            {
                return this.nacionalidadField;
            }
            set
            {
                this.nacionalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string NacionalidadMadre
        {
            get
            {
                return this.nacionalidadMadreField;
            }
            set
            {
                this.nacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string NacionalidadPadre
        {
            get
            {
                return this.nacionalidadPadreField;
            }
            set
            {
                this.nacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string NombreMadre
        {
            get
            {
                return this.nombreMadreField;
            }
            set
            {
                this.nombreMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string NombrePadre
        {
            get
            {
                return this.nombrePadreField;
            }
            set
            {
                this.nombrePadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string NumeroCasa
        {
            get
            {
                return this.numeroCasaField;
            }
            set
            {
                this.numeroCasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string ObservacionInstitucion
        {
            get
            {
                return this.observacionInstitucionField;
            }
            set
            {
                this.observacionInstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string Pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string PaginaDefuncion
        {
            get
            {
                return this.paginaDefuncionField;
            }
            set
            {
                this.paginaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string PaginaMatrimonio
        {
            get
            {
                return this.paginaMatrimonioField;
            }
            set
            {
                this.paginaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string Profesion
        {
            get
            {
                return this.profesionField;
            }
            set
            {
                this.profesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string Tomo
        {
            get
            {
                return this.tomoField;
            }
            set
            {
                this.tomoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string TomoDefuncion
        {
            get
            {
                return this.tomoDefuncionField;
            }
            set
            {
                this.tomoDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string TomoMatrimonio
        {
            get
            {
                return this.tomoMatrimonioField;
            }
            set
            {
                this.tomoMatrimonioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombre", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Genero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        public BusquedaPorNombreRequest()
        {
        }
        
        public BusquedaPorNombreRequest(string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Genero, string Usuario, string Contrasenia)
        {
            this.Apellido1 = Apellido1;
            this.Apellido2 = Apellido2;
            this.Nombre1 = Nombre1;
            this.Nombre2 = Nombre2;
            this.EdadInicio = EdadInicio;
            this.EdadFinal = EdadFinal;
            this.Genero = Genero;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombreResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSRegistroCivil.ciudadanos @return;
        
        public BusquedaPorNombreResponse()
        {
        }
        
        public BusquedaPorNombreResponse(WSRegistroCivil.ciudadanos @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WsUp", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class WsUpRequest
    {
        
        public WsUpRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WsUpResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class WsUpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSRegistroCivil.persona @return;
        
        public WsUpResponse()
        {
        }
        
        public WsUpResponse(WSRegistroCivil.persona @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorCedula", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorCedulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        public BusquedaPorCedulaRequest()
        {
        }
        
        public BusquedaPorCedulaRequest(string Cedula, string Usuario, string Contrasenia)
        {
            this.Cedula = Cedula;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorCedulaResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorCedulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSRegistroCivil.persona @return;
        
        public BusquedaPorCedulaResponse()
        {
        }
        
        public BusquedaPorCedulaResponse(WSRegistroCivil.persona @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombreInscrito", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombreInscritoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Genero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        public BusquedaPorNombreInscritoRequest()
        {
        }
        
        public BusquedaPorNombreInscritoRequest(string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Genero, string Usuario, string Contrasenia)
        {
            this.Apellido1 = Apellido1;
            this.Apellido2 = Apellido2;
            this.Nombre1 = Nombre1;
            this.Nombre2 = Nombre2;
            this.EdadInicio = EdadInicio;
            this.EdadFinal = EdadFinal;
            this.Genero = Genero;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombreInscritoResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombreInscritoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSRegistroCivil.ciudadanos @return;
        
        public BusquedaPorNombreInscritoResponse()
        {
        }
        
        public BusquedaPorNombreInscritoResponse(WSRegistroCivil.ciudadanos @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface WSRegistroCivilConsultaChannel : WSRegistroCivil.WSRegistroCivilConsulta, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class WSRegistroCivilConsultaClient : System.ServiceModel.ClientBase<WSRegistroCivil.WSRegistroCivilConsulta>, WSRegistroCivil.WSRegistroCivilConsulta
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSRegistroCivilConsultaClient() : 
                base(WSRegistroCivilConsultaClient.GetDefaultBinding(), WSRegistroCivilConsultaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSRegistroCivilConsultaPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSRegistroCivilConsultaClient(EndpointConfiguration endpointConfiguration) : 
                base(WSRegistroCivilConsultaClient.GetBindingForEndpoint(endpointConfiguration), WSRegistroCivilConsultaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSRegistroCivilConsultaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSRegistroCivilConsultaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSRegistroCivilConsultaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSRegistroCivilConsultaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSRegistroCivilConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreResponse> WSRegistroCivil.WSRegistroCivilConsulta.BusquedaPorNombreAsync(WSRegistroCivil.BusquedaPorNombreRequest request)
        {
            return base.Channel.BusquedaPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreResponse> BusquedaPorNombreAsync(string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Genero, string Usuario, string Contrasenia)
        {
            WSRegistroCivil.BusquedaPorNombreRequest inValue = new WSRegistroCivil.BusquedaPorNombreRequest();
            inValue.Apellido1 = Apellido1;
            inValue.Apellido2 = Apellido2;
            inValue.Nombre1 = Nombre1;
            inValue.Nombre2 = Nombre2;
            inValue.EdadInicio = EdadInicio;
            inValue.EdadFinal = EdadFinal;
            inValue.Genero = Genero;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            return ((WSRegistroCivil.WSRegistroCivilConsulta)(this)).BusquedaPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSRegistroCivil.WsUpResponse> WSRegistroCivil.WSRegistroCivilConsulta.WsUpAsync(WSRegistroCivil.WsUpRequest request)
        {
            return base.Channel.WsUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSRegistroCivil.WsUpResponse> WsUpAsync()
        {
            WSRegistroCivil.WsUpRequest inValue = new WSRegistroCivil.WsUpRequest();
            return ((WSRegistroCivil.WSRegistroCivilConsulta)(this)).WsUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorCedulaResponse> WSRegistroCivil.WSRegistroCivilConsulta.BusquedaPorCedulaAsync(WSRegistroCivil.BusquedaPorCedulaRequest request)
        {
            return base.Channel.BusquedaPorCedulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorCedulaResponse> BusquedaPorCedulaAsync(string Cedula, string Usuario, string Contrasenia)
        {
            WSRegistroCivil.BusquedaPorCedulaRequest inValue = new WSRegistroCivil.BusquedaPorCedulaRequest();
            inValue.Cedula = Cedula;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            return ((WSRegistroCivil.WSRegistroCivilConsulta)(this)).BusquedaPorCedulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreInscritoResponse> WSRegistroCivil.WSRegistroCivilConsulta.BusquedaPorNombreInscritoAsync(WSRegistroCivil.BusquedaPorNombreInscritoRequest request)
        {
            return base.Channel.BusquedaPorNombreInscritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSRegistroCivil.BusquedaPorNombreInscritoResponse> BusquedaPorNombreInscritoAsync(string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Genero, string Usuario, string Contrasenia)
        {
            WSRegistroCivil.BusquedaPorNombreInscritoRequest inValue = new WSRegistroCivil.BusquedaPorNombreInscritoRequest();
            inValue.Apellido1 = Apellido1;
            inValue.Apellido2 = Apellido2;
            inValue.Nombre1 = Nombre1;
            inValue.Nombre2 = Nombre2;
            inValue.EdadInicio = EdadInicio;
            inValue.EdadFinal = EdadFinal;
            inValue.Genero = Genero;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            return ((WSRegistroCivil.WSRegistroCivilConsulta)(this)).BusquedaPorNombreInscritoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSRegistroCivilConsultaPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSRegistroCivilConsultaPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webservice02.registrocivil.gob.ec:8080/WEBRegistroCivilUniversal/WSRegistr" +
                        "oCivilConsulta");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSRegistroCivilConsultaClient.GetBindingForEndpoint(EndpointConfiguration.WSRegistroCivilConsultaPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSRegistroCivilConsultaClient.GetEndpointAddress(EndpointConfiguration.WSRegistroCivilConsultaPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSRegistroCivilConsultaPort,
        }
    }
}
