using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Text;

namespace ADSAuditsConsumer.DALL.Model
{

    public class LogModel
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        // Id de la transaccion que genera el log

        public string TransactionId { get; set; }

        public string Application { get; set; } = string.Empty;
        // Nivel del log que se genera
        public string LogLevel { get; set; }
        [BsonDateTimeOptions]
        // Fecha de Creacion 
        public DateTime CreateOn { get; set; } = DateTime.Now;
        public string Cuerpo { get; set; }
    }
}
