//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AsegsurPLA", ConfigurationName="PlaService.WSBuscaListaTotalSoapPort")]
    public interface WSBuscaListaTotalSoapPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="AsegsurPLAaction/AWSBUSCALISTATOTAL.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<PlaService.ExecuteResponse> ExecuteAsync(PlaService.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscaListaTotal.Execute", Namespace="AsegsurPLA", Order=0)]
        public PlaService.ExecuteRequestBody Body;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(PlaService.ExecuteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AsegsurPLA")]
    public partial class ExecuteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Praidentificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pranombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Observaciones;
        
        public ExecuteRequestBody()
        {
        }
        
        public ExecuteRequestBody(string Praidentificacion, string Pranombres, string Observaciones)
        {
            this.Praidentificacion = Praidentificacion;
            this.Pranombres = Pranombres;
            this.Observaciones = Observaciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscaListaTotal.ExecuteResponse", Namespace="AsegsurPLA", Order=0)]
        public PlaService.ExecuteResponseBody Body;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(PlaService.ExecuteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AsegsurPLA")]
    public partial class ExecuteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public sbyte Indlista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public sbyte Indautorizacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Listas;
        
        public ExecuteResponseBody()
        {
        }
        
        public ExecuteResponseBody(sbyte Indlista, sbyte Indautorizacion, string Listas)
        {
            this.Indlista = Indlista;
            this.Indautorizacion = Indautorizacion;
            this.Listas = Listas;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface WSBuscaListaTotalSoapPortChannel : PlaService.WSBuscaListaTotalSoapPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class WSBuscaListaTotalSoapPortClient : System.ServiceModel.ClientBase<PlaService.WSBuscaListaTotalSoapPort>, PlaService.WSBuscaListaTotalSoapPort
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSBuscaListaTotalSoapPortClient() : 
                base(WSBuscaListaTotalSoapPortClient.GetDefaultBinding(), WSBuscaListaTotalSoapPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSBuscaListaTotalSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBuscaListaTotalSoapPortClient(EndpointConfiguration endpointConfiguration) : 
                base(WSBuscaListaTotalSoapPortClient.GetBindingForEndpoint(endpointConfiguration), WSBuscaListaTotalSoapPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBuscaListaTotalSoapPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSBuscaListaTotalSoapPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBuscaListaTotalSoapPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSBuscaListaTotalSoapPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBuscaListaTotalSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PlaService.ExecuteResponse> PlaService.WSBuscaListaTotalSoapPort.ExecuteAsync(PlaService.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PlaService.ExecuteResponse> ExecuteAsync(string Praidentificacion, string Pranombres, string Observaciones)
        {
            PlaService.ExecuteRequest inValue = new PlaService.ExecuteRequest();
            inValue.Body = new PlaService.ExecuteRequestBody();
            inValue.Body.Praidentificacion = Praidentificacion;
            inValue.Body.Pranombres = Pranombres;
            inValue.Body.Observaciones = Observaciones;
            return ((PlaService.WSBuscaListaTotalSoapPort)(this)).ExecuteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSBuscaListaTotalSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSBuscaListaTotalSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.1.8/pla/awsbuscalistatotal.aspx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSBuscaListaTotalSoapPortClient.GetBindingForEndpoint(EndpointConfiguration.WSBuscaListaTotalSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSBuscaListaTotalSoapPortClient.GetEndpointAddress(EndpointConfiguration.WSBuscaListaTotalSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSBuscaListaTotalSoapPort,
        }
    }
}
