//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConsultaCiudadano
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.registrocivil.gob.ec", ConfigurationName="WSConsultaCiudadano.ConsultaCiudadano")]
    public interface ConsultaCiudadano
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorNuiIndividual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiIndividualResponse> BusquedaPorNuiIndividualAsync(WSConsultaCiudadano.BusquedaPorNuiIndividual request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorNui", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiResponse> BusquedaPorNuiAsync(WSConsultaCiudadano.BusquedaPorNui request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.registrocivil.gob.ec/BusquedaPorNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNombreResponse> BusquedaPorNombreAsync(WSConsultaCiudadano.BusquedaPorNombre request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.registrocivil.gob.ec")]
    public partial class ciudadano
    {
        
        private string actaField;
        
        private string actaDefuncionField;
        
        private string actaMatrimonioField;
        
        private string anioInscripcionField;
        
        private string apellidosField;
        
        private string calleField;
        
        private string cantonDomicilioField;
        
        private string cantonFallecimientoField;
        
        private string cantonInscripcionField;
        
        private string cantonInscripcionDefuncionField;
        
        private string cantonInscripcionGeneroField;
        
        private string cantonMatrimonioField;
        
        private string cantonNacimientoField;
        
        private string claseField;
        
        private string claseDefuncionField;
        
        private string claseMatrimonioField;
        
        private string codigoCantonDomicilioField;
        
        private string codigoCantonFallecimientoField;
        
        private string codigoCantonInscripcionField;
        
        private string codigoCantonInscripcionDefuncionField;
        
        private string codigoCantonInscripcionGeneroField;
        
        private string codigoCantonMatrimonioField;
        
        private string codigoCantonNacimientoField;
        
        private string codigoCondicionCeduladoField;
        
        private string codigoCondicionDonanteField;
        
        private string codigoDomicilioField;
        
        private string codigoErrorField;
        
        private string codigoEstadoCivilField;
        
        private string codigoGeneroField;
        
        private string codigoGrupoEtnicoField;
        
        private string codigoInstruccionField;
        
        private string codigoLugarDefuncionField;
        
        private string codigoLugarFallecimientoField;
        
        private string codigoLugarInscripcionField;
        
        private string codigoLugarInscripcionGeneroField;
        
        private string codigoLugarMatrimonioField;
        
        private string codigoLugarNacimientoField;
        
        private string codigoNacionalidadField;
        
        private string codigoNacionalidadMadreField;
        
        private string codigoNacionalidadPadreField;
        
        private string codigoPaisDomicilioField;
        
        private string codigoPaisFallecimientoField;
        
        private string codigoPaisInscripcionField;
        
        private string codigoPaisInscripcionDefuncionField;
        
        private string codigoPaisInscripcionGeneroField;
        
        private string codigoPaisMatrimonioField;
        
        private string codigoPaisNacimientoField;
        
        private string codigoParroquiaDomicilioField;
        
        private string codigoParroquiaFallecimientoField;
        
        private string codigoParroquiaInscripcionField;
        
        private string codigoParroquiaInscripcionDefuncionField;
        
        private string codigoParroquiaInscripcionGeneroField;
        
        private string codigoParroquiaMatrimonioField;
        
        private string codigoParroquiaNacimientoField;
        
        private string codigoProfesionField;
        
        private string codigoProvinciaDomicilioField;
        
        private string codigoProvinciaFallecimientoField;
        
        private string codigoProvinciaInscripcionField;
        
        private string codigoProvinciaInscripcionDefuncionField;
        
        private string codigoProvinciaInscripcionGeneroField;
        
        private string codigoProvinciaMatrimonioField;
        
        private string codigoProvinciaNacimientoField;
        
        private string codigoSexoField;
        
        private string codigoTipoCedulaField;
        
        private string condicionCeduladoField;
        
        private string condicionDonanteField;
        
        private string conyugeField;
        
        private string domicilioField;
        
        private string errorField;
        
        private string estadoCivilField;
        
        private string fechaActualizacionField;
        
        private string fechaCedulacionField;
        
        private string fechaFallecimientoField;
        
        private string fechaInscripcionDefuncionField;
        
        private string fechaInscripcionGeneroField;
        
        private string fechaInscripcionNacimientoField;
        
        private string fechaMatrimonioField;
        
        private string fechaNacimientoField;
        
        private byte[] firmaField;
        
        private string firmaElectronicaField;
        
        private byte[] fotografiaField;
        
        private string generoField;
        
        private string grupoEtnicoField;
        
        private string individualDactilarField;
        
        private string instruccionField;
        
        private string lugarDefuncionField;
        
        private string lugarFallecimientoField;
        
        private string lugarInscripcionField;
        
        private string lugarInscripcionGeneroField;
        
        private string lugarMatrimonioField;
        
        private string lugarNacimientoField;
        
        private string nUIField;
        
        private string nacionalidadField;
        
        private string nacionalidadMadreField;
        
        private string nacionalidadPadreField;
        
        private string nombreField;
        
        private string nombreMadreField;
        
        private string nombrePadreField;
        
        private string nombresField;
        
        private string nuiConyugeField;
        
        private string nuiMadreField;
        
        private string nuiPadreField;
        
        private string numeroCasaField;
        
        private string observacionField;
        
        private string observacionInstitucionField;
        
        private string paginaField;
        
        private string paginaDefuncionField;
        
        private string paginaMatrimonioField;
        
        private string paisDomicilioField;
        
        private string paisFallecimientoField;
        
        private string paisInscripcionField;
        
        private string paisInscripcionDefuncionField;
        
        private string paisInscripcionGeneroField;
        
        private string paisMatrimonioField;
        
        private string paisNacimientoField;
        
        private string parroquiaDomicilioField;
        
        private string parroquiaFallecimientoField;
        
        private string parroquiaInscripcionField;
        
        private string parroquiaInscripcionDefuncionField;
        
        private string parroquiaInscripcionGeneroField;
        
        private string parroquiaMatrimonioField;
        
        private string parroquiaNacimientoField;
        
        private string profesionField;
        
        private string provinciaDomicilioField;
        
        private string provinciaFallecimientoField;
        
        private string provinciaInscripcionField;
        
        private string provinciaInscripcionDefuncionField;
        
        private string provinciaInscripcionGeneroField;
        
        private string provinciaMatrimonioField;
        
        private string provinciaNacimientoField;
        
        private string sexoField;
        
        private string tipoCedulaField;
        
        private string tomoField;
        
        private string tomoDefuncionField;
        
        private string tomoMatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Acta
        {
            get
            {
                return this.actaField;
            }
            set
            {
                this.actaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ActaDefuncion
        {
            get
            {
                return this.actaDefuncionField;
            }
            set
            {
                this.actaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ActaMatrimonio
        {
            get
            {
                return this.actaMatrimonioField;
            }
            set
            {
                this.actaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AnioInscripcion
        {
            get
            {
                return this.anioInscripcionField;
            }
            set
            {
                this.anioInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CantonDomicilio
        {
            get
            {
                return this.cantonDomicilioField;
            }
            set
            {
                this.cantonDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CantonFallecimiento
        {
            get
            {
                return this.cantonFallecimientoField;
            }
            set
            {
                this.cantonFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CantonInscripcion
        {
            get
            {
                return this.cantonInscripcionField;
            }
            set
            {
                this.cantonInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CantonInscripcionDefuncion
        {
            get
            {
                return this.cantonInscripcionDefuncionField;
            }
            set
            {
                this.cantonInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CantonInscripcionGenero
        {
            get
            {
                return this.cantonInscripcionGeneroField;
            }
            set
            {
                this.cantonInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CantonMatrimonio
        {
            get
            {
                return this.cantonMatrimonioField;
            }
            set
            {
                this.cantonMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CantonNacimiento
        {
            get
            {
                return this.cantonNacimientoField;
            }
            set
            {
                this.cantonNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Clase
        {
            get
            {
                return this.claseField;
            }
            set
            {
                this.claseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ClaseDefuncion
        {
            get
            {
                return this.claseDefuncionField;
            }
            set
            {
                this.claseDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ClaseMatrimonio
        {
            get
            {
                return this.claseMatrimonioField;
            }
            set
            {
                this.claseMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CodigoCantonDomicilio
        {
            get
            {
                return this.codigoCantonDomicilioField;
            }
            set
            {
                this.codigoCantonDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CodigoCantonFallecimiento
        {
            get
            {
                return this.codigoCantonFallecimientoField;
            }
            set
            {
                this.codigoCantonFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CodigoCantonInscripcion
        {
            get
            {
                return this.codigoCantonInscripcionField;
            }
            set
            {
                this.codigoCantonInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CodigoCantonInscripcionDefuncion
        {
            get
            {
                return this.codigoCantonInscripcionDefuncionField;
            }
            set
            {
                this.codigoCantonInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string CodigoCantonInscripcionGenero
        {
            get
            {
                return this.codigoCantonInscripcionGeneroField;
            }
            set
            {
                this.codigoCantonInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string CodigoCantonMatrimonio
        {
            get
            {
                return this.codigoCantonMatrimonioField;
            }
            set
            {
                this.codigoCantonMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CodigoCantonNacimiento
        {
            get
            {
                return this.codigoCantonNacimientoField;
            }
            set
            {
                this.codigoCantonNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CodigoCondicionCedulado
        {
            get
            {
                return this.codigoCondicionCeduladoField;
            }
            set
            {
                this.codigoCondicionCeduladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string CodigoCondicionDonante
        {
            get
            {
                return this.codigoCondicionDonanteField;
            }
            set
            {
                this.codigoCondicionDonanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CodigoDomicilio
        {
            get
            {
                return this.codigoDomicilioField;
            }
            set
            {
                this.codigoDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string CodigoEstadoCivil
        {
            get
            {
                return this.codigoEstadoCivilField;
            }
            set
            {
                this.codigoEstadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string CodigoGenero
        {
            get
            {
                return this.codigoGeneroField;
            }
            set
            {
                this.codigoGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CodigoGrupoEtnico
        {
            get
            {
                return this.codigoGrupoEtnicoField;
            }
            set
            {
                this.codigoGrupoEtnicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CodigoInstruccion
        {
            get
            {
                return this.codigoInstruccionField;
            }
            set
            {
                this.codigoInstruccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string CodigoLugarDefuncion
        {
            get
            {
                return this.codigoLugarDefuncionField;
            }
            set
            {
                this.codigoLugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string CodigoLugarFallecimiento
        {
            get
            {
                return this.codigoLugarFallecimientoField;
            }
            set
            {
                this.codigoLugarFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string CodigoLugarInscripcion
        {
            get
            {
                return this.codigoLugarInscripcionField;
            }
            set
            {
                this.codigoLugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string CodigoLugarInscripcionGenero
        {
            get
            {
                return this.codigoLugarInscripcionGeneroField;
            }
            set
            {
                this.codigoLugarInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string CodigoLugarMatrimonio
        {
            get
            {
                return this.codigoLugarMatrimonioField;
            }
            set
            {
                this.codigoLugarMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string CodigoLugarNacimiento
        {
            get
            {
                return this.codigoLugarNacimientoField;
            }
            set
            {
                this.codigoLugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string CodigoNacionalidad
        {
            get
            {
                return this.codigoNacionalidadField;
            }
            set
            {
                this.codigoNacionalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string CodigoNacionalidadMadre
        {
            get
            {
                return this.codigoNacionalidadMadreField;
            }
            set
            {
                this.codigoNacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string CodigoNacionalidadPadre
        {
            get
            {
                return this.codigoNacionalidadPadreField;
            }
            set
            {
                this.codigoNacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string CodigoPaisDomicilio
        {
            get
            {
                return this.codigoPaisDomicilioField;
            }
            set
            {
                this.codigoPaisDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string CodigoPaisFallecimiento
        {
            get
            {
                return this.codigoPaisFallecimientoField;
            }
            set
            {
                this.codigoPaisFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string CodigoPaisInscripcion
        {
            get
            {
                return this.codigoPaisInscripcionField;
            }
            set
            {
                this.codigoPaisInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string CodigoPaisInscripcionDefuncion
        {
            get
            {
                return this.codigoPaisInscripcionDefuncionField;
            }
            set
            {
                this.codigoPaisInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string CodigoPaisInscripcionGenero
        {
            get
            {
                return this.codigoPaisInscripcionGeneroField;
            }
            set
            {
                this.codigoPaisInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string CodigoPaisMatrimonio
        {
            get
            {
                return this.codigoPaisMatrimonioField;
            }
            set
            {
                this.codigoPaisMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string CodigoPaisNacimiento
        {
            get
            {
                return this.codigoPaisNacimientoField;
            }
            set
            {
                this.codigoPaisNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string CodigoParroquiaDomicilio
        {
            get
            {
                return this.codigoParroquiaDomicilioField;
            }
            set
            {
                this.codigoParroquiaDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string CodigoParroquiaFallecimiento
        {
            get
            {
                return this.codigoParroquiaFallecimientoField;
            }
            set
            {
                this.codigoParroquiaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string CodigoParroquiaInscripcion
        {
            get
            {
                return this.codigoParroquiaInscripcionField;
            }
            set
            {
                this.codigoParroquiaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string CodigoParroquiaInscripcionDefuncion
        {
            get
            {
                return this.codigoParroquiaInscripcionDefuncionField;
            }
            set
            {
                this.codigoParroquiaInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string CodigoParroquiaInscripcionGenero
        {
            get
            {
                return this.codigoParroquiaInscripcionGeneroField;
            }
            set
            {
                this.codigoParroquiaInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string CodigoParroquiaMatrimonio
        {
            get
            {
                return this.codigoParroquiaMatrimonioField;
            }
            set
            {
                this.codigoParroquiaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string CodigoParroquiaNacimiento
        {
            get
            {
                return this.codigoParroquiaNacimientoField;
            }
            set
            {
                this.codigoParroquiaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string CodigoProfesion
        {
            get
            {
                return this.codigoProfesionField;
            }
            set
            {
                this.codigoProfesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string CodigoProvinciaDomicilio
        {
            get
            {
                return this.codigoProvinciaDomicilioField;
            }
            set
            {
                this.codigoProvinciaDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string CodigoProvinciaFallecimiento
        {
            get
            {
                return this.codigoProvinciaFallecimientoField;
            }
            set
            {
                this.codigoProvinciaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string CodigoProvinciaInscripcion
        {
            get
            {
                return this.codigoProvinciaInscripcionField;
            }
            set
            {
                this.codigoProvinciaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string CodigoProvinciaInscripcionDefuncion
        {
            get
            {
                return this.codigoProvinciaInscripcionDefuncionField;
            }
            set
            {
                this.codigoProvinciaInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string CodigoProvinciaInscripcionGenero
        {
            get
            {
                return this.codigoProvinciaInscripcionGeneroField;
            }
            set
            {
                this.codigoProvinciaInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string CodigoProvinciaMatrimonio
        {
            get
            {
                return this.codigoProvinciaMatrimonioField;
            }
            set
            {
                this.codigoProvinciaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string CodigoProvinciaNacimiento
        {
            get
            {
                return this.codigoProvinciaNacimientoField;
            }
            set
            {
                this.codigoProvinciaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string CodigoSexo
        {
            get
            {
                return this.codigoSexoField;
            }
            set
            {
                this.codigoSexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string CodigoTipoCedula
        {
            get
            {
                return this.codigoTipoCedulaField;
            }
            set
            {
                this.codigoTipoCedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string CondicionCedulado
        {
            get
            {
                return this.condicionCeduladoField;
            }
            set
            {
                this.condicionCeduladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string CondicionDonante
        {
            get
            {
                return this.condicionDonanteField;
            }
            set
            {
                this.condicionDonanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string Conyuge
        {
            get
            {
                return this.conyugeField;
            }
            set
            {
                this.conyugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string Domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string EstadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string FechaActualizacion
        {
            get
            {
                return this.fechaActualizacionField;
            }
            set
            {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string FechaCedulacion
        {
            get
            {
                return this.fechaCedulacionField;
            }
            set
            {
                this.fechaCedulacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string FechaFallecimiento
        {
            get
            {
                return this.fechaFallecimientoField;
            }
            set
            {
                this.fechaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string FechaInscripcionDefuncion
        {
            get
            {
                return this.fechaInscripcionDefuncionField;
            }
            set
            {
                this.fechaInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string FechaInscripcionGenero
        {
            get
            {
                return this.fechaInscripcionGeneroField;
            }
            set
            {
                this.fechaInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string FechaInscripcionNacimiento
        {
            get
            {
                return this.fechaInscripcionNacimientoField;
            }
            set
            {
                this.fechaInscripcionNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string FechaMatrimonio
        {
            get
            {
                return this.fechaMatrimonioField;
            }
            set
            {
                this.fechaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public string FechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=78)]
        public byte[] Firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string FirmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=80)]
        public byte[] Fotografia
        {
            get
            {
                return this.fotografiaField;
            }
            set
            {
                this.fotografiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public string Genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string GrupoEtnico
        {
            get
            {
                return this.grupoEtnicoField;
            }
            set
            {
                this.grupoEtnicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string IndividualDactilar
        {
            get
            {
                return this.individualDactilarField;
            }
            set
            {
                this.individualDactilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=84)]
        public string Instruccion
        {
            get
            {
                return this.instruccionField;
            }
            set
            {
                this.instruccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=85)]
        public string LugarDefuncion
        {
            get
            {
                return this.lugarDefuncionField;
            }
            set
            {
                this.lugarDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=86)]
        public string LugarFallecimiento
        {
            get
            {
                return this.lugarFallecimientoField;
            }
            set
            {
                this.lugarFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=87)]
        public string LugarInscripcion
        {
            get
            {
                return this.lugarInscripcionField;
            }
            set
            {
                this.lugarInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=88)]
        public string LugarInscripcionGenero
        {
            get
            {
                return this.lugarInscripcionGeneroField;
            }
            set
            {
                this.lugarInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=89)]
        public string LugarMatrimonio
        {
            get
            {
                return this.lugarMatrimonioField;
            }
            set
            {
                this.lugarMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=90)]
        public string LugarNacimiento
        {
            get
            {
                return this.lugarNacimientoField;
            }
            set
            {
                this.lugarNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=91)]
        public string NUI
        {
            get
            {
                return this.nUIField;
            }
            set
            {
                this.nUIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=92)]
        public string Nacionalidad
        {
            get
            {
                return this.nacionalidadField;
            }
            set
            {
                this.nacionalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=93)]
        public string NacionalidadMadre
        {
            get
            {
                return this.nacionalidadMadreField;
            }
            set
            {
                this.nacionalidadMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=94)]
        public string NacionalidadPadre
        {
            get
            {
                return this.nacionalidadPadreField;
            }
            set
            {
                this.nacionalidadPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=95)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=96)]
        public string NombreMadre
        {
            get
            {
                return this.nombreMadreField;
            }
            set
            {
                this.nombreMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=97)]
        public string NombrePadre
        {
            get
            {
                return this.nombrePadreField;
            }
            set
            {
                this.nombrePadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=98)]
        public string Nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=99)]
        public string NuiConyuge
        {
            get
            {
                return this.nuiConyugeField;
            }
            set
            {
                this.nuiConyugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=100)]
        public string NuiMadre
        {
            get
            {
                return this.nuiMadreField;
            }
            set
            {
                this.nuiMadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=101)]
        public string NuiPadre
        {
            get
            {
                return this.nuiPadreField;
            }
            set
            {
                this.nuiPadreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=102)]
        public string NumeroCasa
        {
            get
            {
                return this.numeroCasaField;
            }
            set
            {
                this.numeroCasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=103)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=104)]
        public string ObservacionInstitucion
        {
            get
            {
                return this.observacionInstitucionField;
            }
            set
            {
                this.observacionInstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=105)]
        public string Pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=106)]
        public string PaginaDefuncion
        {
            get
            {
                return this.paginaDefuncionField;
            }
            set
            {
                this.paginaDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=107)]
        public string PaginaMatrimonio
        {
            get
            {
                return this.paginaMatrimonioField;
            }
            set
            {
                this.paginaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=108)]
        public string PaisDomicilio
        {
            get
            {
                return this.paisDomicilioField;
            }
            set
            {
                this.paisDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=109)]
        public string PaisFallecimiento
        {
            get
            {
                return this.paisFallecimientoField;
            }
            set
            {
                this.paisFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=110)]
        public string PaisInscripcion
        {
            get
            {
                return this.paisInscripcionField;
            }
            set
            {
                this.paisInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=111)]
        public string PaisInscripcionDefuncion
        {
            get
            {
                return this.paisInscripcionDefuncionField;
            }
            set
            {
                this.paisInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=112)]
        public string PaisInscripcionGenero
        {
            get
            {
                return this.paisInscripcionGeneroField;
            }
            set
            {
                this.paisInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=113)]
        public string PaisMatrimonio
        {
            get
            {
                return this.paisMatrimonioField;
            }
            set
            {
                this.paisMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=114)]
        public string PaisNacimiento
        {
            get
            {
                return this.paisNacimientoField;
            }
            set
            {
                this.paisNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=115)]
        public string ParroquiaDomicilio
        {
            get
            {
                return this.parroquiaDomicilioField;
            }
            set
            {
                this.parroquiaDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=116)]
        public string ParroquiaFallecimiento
        {
            get
            {
                return this.parroquiaFallecimientoField;
            }
            set
            {
                this.parroquiaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=117)]
        public string ParroquiaInscripcion
        {
            get
            {
                return this.parroquiaInscripcionField;
            }
            set
            {
                this.parroquiaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=118)]
        public string ParroquiaInscripcionDefuncion
        {
            get
            {
                return this.parroquiaInscripcionDefuncionField;
            }
            set
            {
                this.parroquiaInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=119)]
        public string ParroquiaInscripcionGenero
        {
            get
            {
                return this.parroquiaInscripcionGeneroField;
            }
            set
            {
                this.parroquiaInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=120)]
        public string ParroquiaMatrimonio
        {
            get
            {
                return this.parroquiaMatrimonioField;
            }
            set
            {
                this.parroquiaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=121)]
        public string ParroquiaNacimiento
        {
            get
            {
                return this.parroquiaNacimientoField;
            }
            set
            {
                this.parroquiaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=122)]
        public string Profesion
        {
            get
            {
                return this.profesionField;
            }
            set
            {
                this.profesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=123)]
        public string ProvinciaDomicilio
        {
            get
            {
                return this.provinciaDomicilioField;
            }
            set
            {
                this.provinciaDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=124)]
        public string ProvinciaFallecimiento
        {
            get
            {
                return this.provinciaFallecimientoField;
            }
            set
            {
                this.provinciaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=125)]
        public string ProvinciaInscripcion
        {
            get
            {
                return this.provinciaInscripcionField;
            }
            set
            {
                this.provinciaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=126)]
        public string ProvinciaInscripcionDefuncion
        {
            get
            {
                return this.provinciaInscripcionDefuncionField;
            }
            set
            {
                this.provinciaInscripcionDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=127)]
        public string ProvinciaInscripcionGenero
        {
            get
            {
                return this.provinciaInscripcionGeneroField;
            }
            set
            {
                this.provinciaInscripcionGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=128)]
        public string ProvinciaMatrimonio
        {
            get
            {
                return this.provinciaMatrimonioField;
            }
            set
            {
                this.provinciaMatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=129)]
        public string ProvinciaNacimiento
        {
            get
            {
                return this.provinciaNacimientoField;
            }
            set
            {
                this.provinciaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=130)]
        public string Sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=131)]
        public string TipoCedula
        {
            get
            {
                return this.tipoCedulaField;
            }
            set
            {
                this.tipoCedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=132)]
        public string Tomo
        {
            get
            {
                return this.tomoField;
            }
            set
            {
                this.tomoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=133)]
        public string TomoDefuncion
        {
            get
            {
                return this.tomoDefuncionField;
            }
            set
            {
                this.tomoDefuncionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=134)]
        public string TomoMatrimonio
        {
            get
            {
                return this.tomoMatrimonioField;
            }
            set
            {
                this.tomoMatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.registrocivil.gob.ec")]
    public partial class ciudadanos
    {
        
        private string codigoErrorField;
        
        private string errorField;
        
        private ciudadano[] personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public ciudadano[] persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNuiIndividual", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNuiIndividual
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoInstitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoAgencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IndividualDactilar;
        
        public BusquedaPorNuiIndividual()
        {
        }
        
        public BusquedaPorNuiIndividual(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string NUI, string IndividualDactilar)
        {
            this.CodigoInstitucion = CodigoInstitucion;
            this.CodigoAgencia = CodigoAgencia;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.NUI = NUI;
            this.IndividualDactilar = IndividualDactilar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNuiIndividualResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNuiIndividualResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSConsultaCiudadano.ciudadano @return;
        
        public BusquedaPorNuiIndividualResponse()
        {
        }
        
        public BusquedaPorNuiIndividualResponse(WSConsultaCiudadano.ciudadano @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNui", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNui
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoInstitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoAgencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUI;
        
        public BusquedaPorNui()
        {
        }
        
        public BusquedaPorNui(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string NUI)
        {
            this.CodigoInstitucion = CodigoInstitucion;
            this.CodigoAgencia = CodigoAgencia;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.NUI = NUI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNuiResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNuiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSConsultaCiudadano.ciudadano @return;
        
        public BusquedaPorNuiResponse()
        {
        }
        
        public BusquedaPorNuiResponse(WSConsultaCiudadano.ciudadano @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombre", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombre
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoInstitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoAgencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellido2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EdadFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sexo;
        
        public BusquedaPorNombre()
        {
        }
        
        public BusquedaPorNombre(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Sexo)
        {
            this.CodigoInstitucion = CodigoInstitucion;
            this.CodigoAgencia = CodigoAgencia;
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.Apellido1 = Apellido1;
            this.Apellido2 = Apellido2;
            this.Nombre1 = Nombre1;
            this.Nombre2 = Nombre2;
            this.EdadInicio = EdadInicio;
            this.EdadFinal = EdadFinal;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusquedaPorNombreResponse", WrapperNamespace="http://www.registrocivil.gob.ec", IsWrapped=true)]
    public partial class BusquedaPorNombreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.registrocivil.gob.ec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSConsultaCiudadano.ciudadanos @return;
        
        public BusquedaPorNombreResponse()
        {
        }
        
        public BusquedaPorNombreResponse(WSConsultaCiudadano.ciudadanos @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface ConsultaCiudadanoChannel : WSConsultaCiudadano.ConsultaCiudadano, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class ConsultaCiudadanoClient : System.ServiceModel.ClientBase<WSConsultaCiudadano.ConsultaCiudadano>, WSConsultaCiudadano.ConsultaCiudadano
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConsultaCiudadanoClient() : 
                base(ConsultaCiudadanoClient.GetDefaultBinding(), ConsultaCiudadanoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ConsultaCiudadanoPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaCiudadanoClient(EndpointConfiguration endpointConfiguration) : 
                base(ConsultaCiudadanoClient.GetBindingForEndpoint(endpointConfiguration), ConsultaCiudadanoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaCiudadanoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConsultaCiudadanoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaCiudadanoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConsultaCiudadanoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaCiudadanoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiIndividualResponse> WSConsultaCiudadano.ConsultaCiudadano.BusquedaPorNuiIndividualAsync(WSConsultaCiudadano.BusquedaPorNuiIndividual request)
        {
            return base.Channel.BusquedaPorNuiIndividualAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiIndividualResponse> BusquedaPorNuiIndividualAsync(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string NUI, string IndividualDactilar)
        {
            WSConsultaCiudadano.BusquedaPorNuiIndividual inValue = new WSConsultaCiudadano.BusquedaPorNuiIndividual();
            inValue.CodigoInstitucion = CodigoInstitucion;
            inValue.CodigoAgencia = CodigoAgencia;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.NUI = NUI;
            inValue.IndividualDactilar = IndividualDactilar;
            return ((WSConsultaCiudadano.ConsultaCiudadano)(this)).BusquedaPorNuiIndividualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiResponse> WSConsultaCiudadano.ConsultaCiudadano.BusquedaPorNuiAsync(WSConsultaCiudadano.BusquedaPorNui request)
        {
            return base.Channel.BusquedaPorNuiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNuiResponse> BusquedaPorNuiAsync(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string NUI)
        {
            WSConsultaCiudadano.BusquedaPorNui inValue = new WSConsultaCiudadano.BusquedaPorNui();
            inValue.CodigoInstitucion = CodigoInstitucion;
            inValue.CodigoAgencia = CodigoAgencia;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.NUI = NUI;
            return ((WSConsultaCiudadano.ConsultaCiudadano)(this)).BusquedaPorNuiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNombreResponse> WSConsultaCiudadano.ConsultaCiudadano.BusquedaPorNombreAsync(WSConsultaCiudadano.BusquedaPorNombre request)
        {
            return base.Channel.BusquedaPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsultaCiudadano.BusquedaPorNombreResponse> BusquedaPorNombreAsync(string CodigoInstitucion, string CodigoAgencia, string Usuario, string Contrasenia, string Apellido1, string Apellido2, string Nombre1, string Nombre2, string EdadInicio, string EdadFinal, string Sexo)
        {
            WSConsultaCiudadano.BusquedaPorNombre inValue = new WSConsultaCiudadano.BusquedaPorNombre();
            inValue.CodigoInstitucion = CodigoInstitucion;
            inValue.CodigoAgencia = CodigoAgencia;
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.Apellido1 = Apellido1;
            inValue.Apellido2 = Apellido2;
            inValue.Nombre1 = Nombre1;
            inValue.Nombre2 = Nombre2;
            inValue.EdadInicio = EdadInicio;
            inValue.EdadFinal = EdadFinal;
            inValue.Sexo = Sexo;
            return ((WSConsultaCiudadano.ConsultaCiudadano)(this)).BusquedaPorNombreAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaCiudadanoPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaCiudadanoPort))
            {
                return new System.ServiceModel.EndpointAddress("https://wsprodu.registrocivil.gob.ec/WsRegistroCivil/ConsultaCiudadano");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultaCiudadanoClient.GetBindingForEndpoint(EndpointConfiguration.ConsultaCiudadanoPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultaCiudadanoClient.GetEndpointAddress(EndpointConfiguration.ConsultaCiudadanoPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ConsultaCiudadanoPort,
        }
    }
}
