using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json.Linq;

namespace ADSAudits.DAL.Models
{

 
    public class LogModel
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        // Id de la transaccion que genera el log
        
        public string TransactionId { get; set; }

        public string Application { get; set; } = string.Empty;
        // Nivel del log que se genera
        public int LogLevel { get; set; } = 0;
        [BsonDateTimeOptions]
        // Fecha de Creacion 
        public DateTime CreateOn { get; set; } = DateTime.Now;
        public String Cuerpo { get; set; }
    }

}
