using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json.Linq;

namespace ADSAudits.DAL.Models
{

 
    public class LogModel
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }
        public string TraceId { get; set; }
        public string Service { get; set; }
        public string LogLevel { get; set; }
        public int EventId { get; set; }
        public object LogDetail { get; set; }
        public string Message { get; set; }
        public DateTime CreateOn { get; set; } = DateTime.Now;
    }

}
